version: '3'

services:
  php:
    image: baip/fhimpg-archive
    restart: always
    ports:
      - 80:80
    volumes:
      - ./data:/a/data
      - ./archive.conf:/a/www/archive.conf
      - ./000-default.conf:/etc/apache2/sites-enabled/000-default.conf
    depends_on:
      - mysql

  mysql:
    image: mariadb
    restart: always
    cap_add:
      - SYS_NICE  # CAP_SYS_NICE
    env_file:
      - db.env
    volumes:
      - ./mysql:/var/lib/mysql